words_manager/urls.py
from django.urls import path
from . import views


app_name = 'words_manager'
urlpatterns = [
    # Views
    path('all/', views.sets_display, name='sets_display'),
    path('add/', views.set_add, name='set_add'),
    path('<int:set_id>/', views.set_display, name='set_display'),
    path('<int:set_id>/edit/', views.set_edit, name='set_edit'),
    path('<int:set_id>/add/', views.word_add, name='word_add'),
    path('word/<int:word_id>/edit/', views.word_edit, name='word_edit'),

    # They aren't views
    path('<int:set_id>/delete/', views.set_delete, name='set_delete'),
    path('word/<int:word_id>/delete/', views.word_delete, name='word_delete'),
]

words_manager/models.py
from django.db import models

class Set(models.Model):
    name = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Word(models.Model):
    set_FK = models.ForeignKey(Set, on_delete=models.CASCADE)

    '''   --- Memobox Legend ---
        0       is not already learning
        1 - 5   is in memobex
        6       words have learned
    '''
    memobox = models.IntegerField(default=1)

    foreign_word = models.CharField(max_length=30)
    native_word = models.CharField(max_length=30)

    native_word_other = models.TextField(blank=True, default='')

    foreign_example = models.TextField(blank=True, default='')
    native_example = models.TextField(blank=True, default='')

    def __str__(self):
        return self.foreign_word

words_manager/forms.py
from django import forms
from .models import Set, Word


class SetForm(forms.ModelForm):
    class Meta:
        model = Set
        fields = ['name']
        labels = {'text': ''}
        widgets = {'name': forms.TextInput(attrs={'id':'form_name'})}
        


class WordForm(forms.ModelForm):
    class Meta: 
        model = Word

        fields = [
            # NOT NULL
            'foreign_word',
            'native_word',

            # CAN BE NULL
            'native_word_other',
            'foreign_example',
            'native_example',
        ]

        labels = {
            'foreign_word': '',
            'native_word': '',
            'native_word_other': '',
            'foreign_example': '',
            'native_example': '',
        }

        widgets = {
            'foreign_word': forms.Textarea(attrs={
                'class': 'add_word_input required',
                'cols': 30,
                'rows': 1,
                'placeholder': 'foreign word',
            }),

            'native_word': forms.Textarea(attrs={
                'class': 'add_word_input required',
                'cols': 30,
                'rows': 1,
                'placeholder': 'native word',
            }),

            'native_word_other': forms.Textarea(attrs={
                'class': 'add_word_input optional',
                'cols': 30,
                'rows': 1,
                'placeholder': 'optional native word',
            }),

            'foreign_example': forms.Textarea(attrs={
                'class': 'add_word_input space optional',
                'cols': 40,
                'rows': 1,
                'placeholder': 'foreign example sentence',
            }),

            'native_example': forms.Textarea(attrs={
                'class': 'add_word_input optional',
                'cols': 40,
                'rows': 1,
                'placeholder': 'meaning',
            }),
        }

words_manager/views.py
# Functions import
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
#from django.http import Http404

# Objects import
from .models import *

# Forms import
from .forms import SetForm, WordForm


def sets_display(request):
    sets = Set.objects.order_by('-date_added')
    return render(request, 'words_manager/sets_display.html', {'sets': sets})


def set_add(request):
    if request.method != 'POST':
        form = SetForm()
    else:
        form = SetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('words_manager:sets_display'))

    return render(request, 'words_manager/set_add.html', {'form': form})


def set_display(request, set_id):
    spec_set = get_object_or_404(Set, pk=set_id)

    words = spec_set.word_set.all()
    context = {'set': spec_set, 'words': words}
    return render(request, 'words_manager/set_display.html', context)


def set_edit(request, set_id):
    spec_set = get_object_or_404(Set, pk=set_id)

    words = spec_set.word_set.all()
    context = {'set': spec_set, 'words': words}
    return render(request, 'words_manager/set_edit.html', context)


def word_add(request, set_id):
    spec_set = get_object_or_404(Set, pk=set_id)

    if request.method != 'POST':
        form = WordForm()
    else:
        form = WordForm(request.POST)
        if form.is_valid():
            new_words = form.save(commit=False)
            new_words.set_FK = spec_set
            new_words.save()
            return redirect(reverse('words_manager:set_edit', args=[set_id]))

    context = {
        'form': form,
        'set': spec_set,
    }

    return render(request, 'words_manager/word_add.html', context)


def word_edit(request, word_id):
    spec_word = get_object_or_404(Word, pk=word_id)
    spec_set = spec_word.set_FK

    if request.method != 'POST':
        form = WordForm(instance=spec_word)
    else:
        form = WordForm(request.POST, instance=spec_word)
        if form.is_valid():
            form.save()
            return redirect(reverse('words_manager:set_edit', args=[spec_set.id]))

    context = {
        'form': form,
        'word': spec_word,
    }

    return render(request, 'words_manager/word_edit.html', context)


def set_delete(request, set_id):
    spec_set = Set.objects.get(id=set_id)
    spec_set.delete()
    return redirect(reverse('words_manager:sets_display'))


def word_delete(request, word_id):
    spec_word = Word.objects.get(id=word_id)
    spec_set = spec_word.set_FK
    spec_word.delete()
    return redirect(reverse('words_manager:set_display', args=[spec_set.id]))

words_manager/templates/words_manager/base.html
{% load static %}
<html lang="en">
<head>
    <!-- Meta data -->
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta name="description" content="Modern web application allowing users to learn words in foreign languages.">
    <meta name="keywords" content="ingest, words app, learn words, flashcards, studing, english,
    german, italian, french, spanish, school, school tool, polish, quizlet, anki">

    <!-- <title>INGEST</title> -->

    <!-- stylesheets and more -->
    <link href="{% static 'words_manager/css/base.css' %} " rel="stylesheet" type="text/css" />
    <link href="{% static 'words_manager/css/animation.css' %} " rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'words_manager/images/favicon.png' %}" type="image/x-icon" />

    {% block head %} {% endblock head %}

</head>

<body>
<div class="area">
    <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>
<nav>
    <div id="navigation_bar">
        <a href="{% url 'words_manager:sets_display' %}"><img src="{% static 'words_manager/images/ingest.svg' %}" alt="app logo" id="logo"></a>
        <p id="user_name">-LOGIN OF USER-</p>
        <img id="logout_icon" src="{% static 'words_manager/icons/user_panel_navigation_bar_icons/logout_icon.png' %}" alt="logout icon">
    </div>
    <div id="navigation_bar_border"></div>
</nav>
<aside>
    <div class="side_bar">
        <img src="{% static 'words_manager/icons/side_bar_icons/user_icon.png' %}" class="user_icon" alt="go to the profile icon">
        <img src="{% static 'words_manager/icons/side_bar_icons/email_icon.png' %}" class="user_icon" alt="send us a message icon">
        <img src="{% static 'words_manager/icons/side_bar_icons/settings_icon.png' %}" class="user_icon" alt="go to the settings icon">
    </div>
</aside>
    {% block content %}

    {% endblock content %}
</body>

</html>
<!--Background Pattern: url("https://www.transparenttextures.com/patterns/swirl.png")-->
<!--Flags Icons made by Freepik from www.flaticon.com-->
<!--Round Icons download from streamlneicons.com-->

words_manager/templates/words_manager/set_add.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link href="{% static 'words_manager/css/set_add.css'%}" rel="stylesheet" type="text/css" /> {% endblock head %} {% block content %}

<div id="new_set_content">
    <section>
        <header>
            <h1 id="new_set_title_row_h1">NEW SET</h1>
        </header>
        <form action="{% url 'words_manager:set_add' %}" method="POST">

            {% csrf_token %}
            <div class="set_title">
                {{ form.as_p }}
            </div>

            <button name="submit" id="new_set_button">CREATE SET</button>
        </form>
    </section>
</div>

{% endblock content %}

words_manager/templates/words_manager/set_display.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'words_manager/css/set_display.css' %}" type="text/css" /> {% endblock head %} {% block content %}

<div id="specific_set_content">
    <section>
        <div id="specific_set_rectangle">
            <header>
                <h1 id="specific_set_title_row_h1">{{set}}</h1>
            </header>
            <article>
                <div id="words_list">
                    <ul id="words_list_ul">
                        {% for word in words %}

                        <li class="specific_set_list_li">{{ word }} - {{ word.native_word }}</li>

                        {% empty %}

                        <li class="specific_set_list_li">Set {{ set }} is empty</li>

                        {% endfor %}
                    </ul>
                </div>
            </article>
            <article>
                <button id="start_button">START</button>

                <a href="{% url 'words_manager:set_edit' set.id %}">
                    <button id="edit_button">EDIT</button>
                </a>

                <a href="{% url 'words_manager:set_delete' set.id %}">
                    <button id="delete_button">DELETE</button>
                </a>

            </article>
        </div>
    </section>
</div>

{% endblock content %}

words_manager/templates/words_manager/set_edit.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'words_manager/css/set_edit.css' %}" type="text/css" /> {% endblock head %} {% block content %}
<main>
<div id="edit_set_content">
    <div id="edit_set_rectangle">
        <header>
            <h1 id="edit_set_title_row_h1">Edit {{ set }}</h1>
        </header>
        <article>
        <div id="words_list">
            <ul id="words_list_ul">

                {% for word in words %}

                <li class="words_list_li">{{ word }} - {{ word.native_word }}
                    <a href="{% url 'words_manager:word_edit' word.id %}">
                        <button class="edit_word_button">edit</button>
                    </a>

                    <a href="{% url 'words_manager:word_delete' word.id %}">
                        <button class="delete_word_button">delete</button>
                    </a>
                </li>

                {% empty %}

                <li class="words_list_li">Set {{ set }} is empty</li>

                {% endfor %}

            </ul>
        </div>
        </article>

        <article>
        <a>
        <button id="edit_button">EDIT TITLE</button>
        </a>

        <a href="{% url 'words_manager:word_add' set.id %}">
            <button id="undo_button">ADD WORD</button>
        </a>
        </article>

    </div>
</div>
</main>
{% endblock content %}

words_manager/templates/words_manager/set_edit_title.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'words_manager/css/set_edit_title.css' %}" type="text/css" /> {% endblock head %} {% block content %}
<main>
<div id="edit_set_content">
    <div id="edit_set_rectangle">
        <header>
            <h1 id="edit_set_title_row_h1">Edit {{ set }}</h1>
        </header>
        <article>
        <div id="words_list">
            <!--  STEPKOS WORk  -->
        </div>

        <button id="edit_button">EDIT TITLE</button>
        <a href="{% url 'words_manager:word_add' set.id %}">
        </a>
        </article>
    </div>
</div>
</main>
{% endblock content %}

words_manager/templates/words_manager/sets_display.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link href="{% static 'words_manager/css/sets_display.css'%}" rel="stylesheet" type="text/css" /> {% endblock head %} {% block content %}
<main>
    <div id="my_sets_content">
        <section>
            <div id="my_sets_rectangle">
                <header>
                    <h1 id="my_sets_title_row_h1">MY SETS</h1>
                </header>
                <article>
                    <ul id="set_list_ul">

                        {% for set in sets %}

                        <li class="set_list_li">
                            <a href="{% url 'words_manager:set_display' set.id %}">
                                {{ set }}
                            </a>
                        </li>

                        {% endfor %}

                    </ul>

                    <span id="add_new_set_plus_icon">
                    <a href="{% url 'words_manager:set_add'%}">
                    <i class="fas fa-plus-circle fa-3x"></i>
                </a>
                </span>

                </article>
            </div>
        </section>

    </div>
</main>
{% endblock content %}

words_manager/templates/words_manager/word_add.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link href="{% static 'words_manager/css/word_add.css'%}" rel="stylesheet" type="text/css" /> {% endblock head %} {% block content %}

<div id="new_word_content">
    <section>
        <header>
            <h1 id="new_word_title_row_h1">NEW WORD</h1>
        </header>

        <form action="{% url 'words_manager:word_add' set.id %}" method="POST">
            {% csrf_token %} {{ form.as_p }}
            <button name="submit" id="new_word_button">Add Word</button>
        </form>

    </section>
</div>

{% endblock content %}

words_manager/templates/words_manager/word_edit.html
{% extends "words_manager/base.html" %} {% load static %} {% block head %}
<link href="{% static 'words_manager/css/set_add.css'%}" rel="stylesheet" type="text/css" /> {% endblock head %} {% block content %}

<div id="new_set_content">
    <section>
        <header>
            <h1 id="new_set_title_row_h1">EDIT WORD</h1>
        </header>

        <form action="{% url 'words_manager:word_edit' word.id %}" method="POST">
            {% csrf_token %} {{ form.as_p }}
            <button name="submit">Edit Word</button>
        </form>

    </section>
</div>

{% endblock content %}